name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS_EC2

    steps:
      - name: Checkout Repository #取得最新代碼
        uses: actions/checkout@v2

      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Backend
            git pull git@github.com:Lishin1215/Flood-Monitor-backend.git main
            sudo docker stop flood-monitor || true
            sudo docker rm flood-monitor || true
            sudo docker build -t flood-monitor .
            sudo docker run --env-file .env -d -p 5000:5000 flood-monitor
            sudo systemctl restart nginx

